package com.zmap.zmap.mapper;

import com.zmap.zmap.model.PatientRegistration;
import com.zmap.zmap.model.PatientRegistrationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PatientRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientregistration
     *
     * @mbg.generated
     */
    int insert(PatientRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientregistration
     *
     * @mbg.generated
     */
    int insertSelective(PatientRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientregistration
     *
     * @mbg.generated
     */
    List<PatientRegistration> selectByExample(PatientRegistrationExample example);
}