package com.zmap.zmap.model;

import java.util.Date;

public class PatientRegistration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.original_id
     *
     * @mbg.generated
     */
    private String originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.registration_number
     *
     * @mbg.generated
     */
    private Integer registrationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.registration_time
     *
     * @mbg.generated
     */
    private Date registrationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.doctor_id
     *
     * @mbg.generated
     */
    private String doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.serviceDepartment_id
     *
     * @mbg.generated
     */
    private String servicedepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.patient_card_number
     *
     * @mbg.generated
     */
    private String patientCardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientregistration.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.id
     *
     * @return the value of patientregistration.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.id
     *
     * @param id the value for patientregistration.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.original_id
     *
     * @return the value of patientregistration.original_id
     *
     * @mbg.generated
     */
    public String getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.original_id
     *
     * @param originalId the value for patientregistration.original_id
     *
     * @mbg.generated
     */
    public void setOriginalId(String originalId) {
        this.originalId = originalId == null ? null : originalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.registration_number
     *
     * @return the value of patientregistration.registration_number
     *
     * @mbg.generated
     */
    public Integer getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.registration_number
     *
     * @param registrationNumber the value for patientregistration.registration_number
     *
     * @mbg.generated
     */
    public void setRegistrationNumber(Integer registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.registration_time
     *
     * @return the value of patientregistration.registration_time
     *
     * @mbg.generated
     */
    public Date getRegistrationTime() {
        return registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.registration_time
     *
     * @param registrationTime the value for patientregistration.registration_time
     *
     * @mbg.generated
     */
    public void setRegistrationTime(Date registrationTime) {
        this.registrationTime = registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.doctor_id
     *
     * @return the value of patientregistration.doctor_id
     *
     * @mbg.generated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.doctor_id
     *
     * @param doctorId the value for patientregistration.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.serviceDepartment_id
     *
     * @return the value of patientregistration.serviceDepartment_id
     *
     * @mbg.generated
     */
    public String getServicedepartmentId() {
        return servicedepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.serviceDepartment_id
     *
     * @param servicedepartmentId the value for patientregistration.serviceDepartment_id
     *
     * @mbg.generated
     */
    public void setServicedepartmentId(String servicedepartmentId) {
        this.servicedepartmentId = servicedepartmentId == null ? null : servicedepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.patient_card_number
     *
     * @return the value of patientregistration.patient_card_number
     *
     * @mbg.generated
     */
    public String getPatientCardNumber() {
        return patientCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.patient_card_number
     *
     * @param patientCardNumber the value for patientregistration.patient_card_number
     *
     * @mbg.generated
     */
    public void setPatientCardNumber(String patientCardNumber) {
        this.patientCardNumber = patientCardNumber == null ? null : patientCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.create_time
     *
     * @return the value of patientregistration.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.create_time
     *
     * @param createTime the value for patientregistration.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientregistration.update_time
     *
     * @return the value of patientregistration.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientregistration.update_time
     *
     * @param updateTime the value for patientregistration.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}